/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yhsh_songlib_SongUtils */

#ifndef _Included_cn_yhsh_songlib_SongUtils
#define _Included_cn_yhsh_songlib_SongUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yhsh_songlib_SongUtils
 * Method:    duration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yhsh_songlib_SongUtils_duration
  (JNIEnv *, jclass);

/*
 * Class:     cn_yhsh_songlib_SongUtils
 * Method:    length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_yhsh_songlib_SongUtils_length
  (JNIEnv *, jclass);

/*
 * Class:     cn_yhsh_songlib_SongUtils
 * Method:    songIo
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_yhsh_songlib_SongUtils_songIo
  (JNIEnv *, jclass);

/*
 * Class:     cn_yhsh_songlib_SongUtils
 * Method:    coverSong
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_yhsh_songlib_SongUtils_coverSong
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
