/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yhsh_songlib_SongUtils */

#ifndef _Included_cn_yhsh_songlib_SongUtils
#define _Included_cn_yhsh_songlib_SongUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yhsh_songlib_SongUtils
 * Method:    duration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_yhsh_songlib_SongUtils_duration(JNIEnv *env, jclass objt) {
    //返回一个字符串类型，对应SongUtils.java文件里面的方法
    return (*env)->NewStringUTF(env, "Android 我来了!");
}

JNIEXPORT jint JNICALL Java_cn_yhsh_songlib_SongUtils_length(JNIEnv *env, jclass clazz) {
    //返回一个int类型，对应SongUtils.java文件里面的方法
    return 100;
}

JNIEXPORT jbyteArray JNICALL Java_cn_yhsh_songlib_SongUtils_songIo(JNIEnv *env, jclass clazz) {

//    jbyteArray result = (*env)->NewByteArray(env, 100);
//    (*env)->SetByteArrayRegion(result, 0, 10, 23, (const jbyte *) 13);
//    return result;
    //返回一个byte数组类型，对应SongUtils.java文件里面的方法
    return (*env)->NewByteArray(env, 101);
}

JNIEXPORT jbyteArray JNICALL
Java_cn_yhsh_songlib_SongUtils_coverSong(JNIEnv *env, jclass clazz, jbyteArray data) {
//    jbyteArray d = (*env)->NewByteArray(env, 132);
    //返回一个byte数组类型，对应SongUtils.java文件里面的方法
    return data;
}

#ifdef __cplusplus
}
#endif
#endif
